/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a customer user and their customer profile */
        post: operations["auth.register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and issue a Sanctum token */
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout the current token */
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated user profile */
        get: operations["auth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List customers with pagination */
        get: operations["customers.index"];
        put?: never;
        /** Create a new customer */
        post: operations["customers.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{customer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show a single customer */
        get: operations["customers.show"];
        /** Update customer details */
        put: operations["customers.update"];
        post?: never;
        /** Delete a customer record */
        delete: operations["customers.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders with related customer and items */
        get: operations["order.index"];
        put?: never;
        /** Place a new order using validated items and credit checks */
        post: operations["order.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show a single order with related customer and items */
        get: operations["order.show"];
        /** Update order fields such as due date or payment flag */
        put: operations["order.update"];
        post?: never;
        /** Delete an order record */
        delete: operations["order.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel an order before delivery and restore customer credit */
        post: operations["order.cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List order items with related order and product */
        get: operations["order-items.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/order-items/{orderItem}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show a single order item with its relations */
        get: operations["order-items.show"];
        /** Update delivery status for an order item */
        put: operations["order-items.update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products with pagination */
        get: operations["product.index"];
        put?: never;
        /** Create a product and upload optional image array */
        post: operations["product.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show a single product */
        get: operations["product.show"];
        /** Update product details and replace images if provided */
        put: operations["product.update"];
        post?: never;
        /** Delete a product and its stored images */
        delete: operations["product.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/redeem-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new redeem code with a fixed amount */
        post: operations["redeemCode.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/redeem-codes/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem a code and top up customer credit */
        post: operations["redeemCode.redeem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reorder-notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reorder notices with pagination */
        get: operations["reorderNotice.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reorder-notices/{reorderNotice}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Show a single reorder notice */
        get: operations["reorderNotice.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CustomerResource */
        CustomerResource: {
            customerID: number;
            first_name: string;
            middle_name: string;
            last_name: string;
            address: {
                house_no: string;
                street_name: string;
                city: string;
                zip_code: string;
            };
            phone: string;
            credit_limit: string;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /**
         * DeliveryStatus
         * @enum {string}
         */
        DeliveryStatus: "pending" | "delivered";
        /** LengthAwarePaginator */
        LengthAwarePaginator: {
            current_page: number;
            data: string;
            first_page_url: string;
            from: number | null;
            last_page: number;
            last_page_url: string;
            links: {
                [key: string]: unknown;
            };
            next_page_url: string;
            path: string | null;
            per_page: number;
            prev_page_url: string | null;
            to: number | null;
            total: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** OrderItemResource */
        OrderItemResource: {
            orderItemID: number;
            orderID: number;
            productID: number;
            quantity: number;
            itemTotalPrice: string;
            deliveryStatus: components["schemas"]["DeliveryStatus"];
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            product?: components["schemas"]["ProductResource"];
        };
        /** OrderResource */
        OrderResource: {
            orderID: number;
            customerID: number;
            totalPrice: string;
            dueDate: string;
            orderStatus: components["schemas"]["OrderStatus"];
            isPaid: boolean;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
            customer?: components["schemas"]["CustomerResource"];
            items?: components["schemas"]["OrderItemResource"][];
        };
        /**
         * OrderStatus
         * @enum {string}
         */
        OrderStatus: "pending" | "processing" | "completed" | "cancelled";
        /** ProductResource */
        ProductResource: {
            productID: number;
            name: string;
            description: string;
            costPrice: string;
            sellPrice: string;
            currentQuantity: number;
            reorderLevel: number;
            reorderQuantity: number;
            images: string[];
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /** RedeemCodeRequest */
        RedeemCodeRequest: {
            customerID: number;
            code: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            first_name: string;
            middle_name: string;
            last_name: string;
            house_no: string;
            street_name: string;
            city: string;
            zip_code: string;
            phone: string;
            password_confirmation: string;
        };
        /** ReorderNotice */
        ReorderNotice: {
            id: number;
            productID: number;
            productName: string;
            reorderQuantity: number;
            currentQuantity: number;
            isResolved: boolean;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /** StoreCustomerRequest */
        StoreCustomerRequest: {
            first_name: string;
            middle_name: string;
            last_name: string;
            phone: string;
            house_no: string;
            street_name: string;
            city: string;
            zip_code: string;
            credit_limit: number;
        };
        /** StoreOrderRequest */
        StoreOrderRequest: {
            customerID: number;
            /** Format: date-time */
            dueDate: string;
            items: {
                productID: number;
                quantity: number;
            }[];
        };
        /** StoreProductRequest */
        StoreProductRequest: {
            name: string;
            description: string;
            costPrice: number;
            sellPrice: number;
            currentQuantity: number;
            reorderLevel: number;
            reorderQuantity: number;
            images?: string[] | null;
        };
        /** StoreRedeemCodeRequest */
        StoreRedeemCodeRequest: {
            code?: string;
            amount: number;
        };
        /** UpdateCustomerRequest */
        UpdateCustomerRequest: {
            first_name?: string;
            middle_name?: string;
            last_name?: string;
            house_no?: string;
            street_name?: string;
            city?: string;
            zip_code?: string;
            phone?: string;
            credit_limit?: number;
        };
        /** UpdateOrderItemRequest */
        UpdateOrderItemRequest: {
            deliveryStatus: components["schemas"]["DeliveryStatus"];
        };
        /** UpdateOrderRequest */
        UpdateOrderRequest: {
            /** Format: date-time */
            dueDate?: string;
            isPaid?: boolean;
        };
        /** UpdateProductRequest */
        UpdateProductRequest: {
            name?: string;
            description?: string;
            costPrice?: number;
            sellPrice?: number;
            currentQuantity?: number;
            reorderLevel?: number;
            reorderQuantity?: number;
            images?: string[] | null;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth.register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: {
                            user: {
                                id: string;
                                name: string;
                                email: string;
                                role: string;
                            };
                            customer: components["schemas"]["CustomerResource"] | null;
                            token: string;
                        };
                    };
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "error";
                        /** @enum {string} */
                        message: "Invalid credentials.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: null;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: {
                            user: {
                                id: number;
                                name: string;
                                email: string;
                                role: string;
                            };
                            customer: components["schemas"]["CustomerResource"] | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "customers.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["CustomerResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "customers.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreCustomerRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["CustomerResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "customers.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The customer customerid */
                customer: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["CustomerResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "customers.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The customer customerid */
                customer: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["CustomerResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "customers.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The customer customerid */
                customer: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: null;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "order.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["LengthAwarePaginator"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "error";
                        /** @enum {string} */
                        message: "No customer profile linked to this account.";
                    };
                };
            };
        };
    };
    "order.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreOrderRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["OrderResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "error";
                        /** @enum {string} */
                        message: "Only customers can place orders.";
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "order.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order orderid */
                order: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["OrderResource"];
                    } | null;
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "error";
                        /** @enum {string} */
                        message: "Forbidden.";
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "order.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order orderid */
                order: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateOrderRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["OrderResource"];
                    } | null;
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "error";
                        /** @enum {string} */
                        message: "Forbidden.";
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "order.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order orderid */
                order: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        /** @enum {string} */
                        message: "Order deleted successfully";
                    } | null;
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "error";
                        /** @enum {string} */
                        message: "Forbidden.";
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "order.cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order orderid */
                order: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "order-items.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["OrderItemResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "order-items.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order item orderitemid */
                orderItem: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["OrderItemResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "order-items.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The order item orderitemid */
                orderItem: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderItemRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["OrderItemResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "product.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["ProductResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "product.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["StoreProductRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["ProductResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "product.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The product productid */
                product: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["ProductResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "product.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The product productid */
                product: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["UpdateProductRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["ProductResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "product.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The product productid */
                product: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        /** @enum {string} */
                        message: "Product deleted successfully";
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "redeemCode.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreRedeemCodeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: {
                            code: string;
                            amount: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "redeemCode.redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemCodeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: {
                            code: string;
                            amount: string;
                            /** Format: date-time */
                            usedAt: string | null;
                            usedByCustomerID: number | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "error";
                        /** @enum {string} */
                        message: "No customer profile linked to this account.";
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "reorderNotice.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["LengthAwarePaginator"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "reorderNotice.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The reorder notice ID */
                reorderNotice: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "success";
                        data: components["schemas"]["ReorderNotice"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
}
